//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.dossierAdmissions = new HashSet<dossierAdmission>();
        }
    
        public string nss { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string province { get; set; }
        public string codePostal { get; set; }
        public string telephone { get; set; }
        public string idMedecin { get; set; }
        public string idCompanie { get; set; }
        public string refParent { get; set; }
    
        public virtual Assurance Assurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dossierAdmission> dossierAdmissions { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
